FROM rust:1.90-slim-bullseye

RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    libudev-dev \
    && rm -rf /var/lib/apt/lists/*

# Install tools for Pico 2W
RUN rustup target add thumbv8m.main-none-eabihf && \
    cargo install elf2uf2-rs --locked

WORKDIR /workspace
CMD ["tail", "-f", "/dev/null"]