services:
  rust-dev:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ..
      dockerfile: .docker/Dockerfile.rust
    container_name: rpi_pico_dev
    volumes:
      - ../:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    working_dir: /workspace
    environment:
      - CARGO_TARGET_DIR=/workspace/target
    stdin_open: true
    tty: true

volumes:
  cargo-cache:
  target-cache: